### ISSUE TITLE
Condition to win the match

### ISSUE THREAD

**Issue by EduardoNunes5** [EduardoNunes5/TicTacToe#3]
There's a bug when the player should win the match when it comes to up-to-bottom. eg.:
X 0 X
X 0  0
X 
^

**Comment by Manan311** [comment]
Hey	EduardoNunes5a, if this problem is still up for grab I would like to take a crack at it if possible.

**Comment by EduardoNunes5** [comment]
> Hey EduardoNunes5a, if this problem is still up for grab I would like to take a crack at it if possible.
Yeah, it is. thanks for helping. Just send a pull request :)
